version: '3.7'

# 使用 directus + mysql 构建本地开发环境
services:
  directus_db_container:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - directus_db_data_container:/var/lib/mysql
  directus_adminer_db_container:
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: directus_db_container
    ports:
      - 8080:8080
  directus:
    image: directus/directus:latest
    ports:
      - 8055:8055
    volumes:
      - ./uploads:/directus/uploads
    depends_on:
      - directus_db_container
    environment:
      KEY: '255d861b-5ea1-5996-9aa3-922530ec40b1'
      SECRET: '6116487b-cda1-52c2-b5b5-c8022c45e263'

      DB_CLIENT: 'mysql'
      DB_HOST: 'directus_db_container'
      DB_PORT: '3306'
      DB_DATABASE: 'vnav'
      DB_USER: 'root'
      DB_PASSWORD: 'root'

      ADMIN_EMAIL: 'admin@example.com'
      ADMIN_PASSWORD: '123456'

volumes:
  directus_db_data_container: