version: '3.7'

services:
  directus:
    image: directus/directus:latest
    ports:
      - 8055:8055
    volumes:
      - vnav_uploads:/directus/uploads
    environment:
      KEY: '255d861b-5ea1-5996-9aa3-922530ec40b1'
      SECRET: '6116487b-cda1-52c2-b5b5-c8022c45e263'
    env_file: .env

  vnav:
    build:
      context: .
      dockerfile: Dockerfile
    image: vnav
    ports:
      - "3000:3000"

volumes:
  vnav_uploads: